apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Welcome to Nginx v2</title>
    </head>
    <body>
      <h1>Hello, World from Nginx Bug v2!</h1>
    </body>
    </html>
