apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app-nfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-app
        image: teknikhub/web-v1-php:v4
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-html
          mountPath: /mnt/nfs
      volumes:
      - name: nginx-html
        nfs:
          server: 192.168.1.24
          path: /root/nfs/nginx
